<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2Oi7Ymf' shared service.

return $this->privates['.service_locator.2Oi7Ymf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EntrepriseController::depot' => ['privates', '.service_locator.aqPYyD2', 'get_ServiceLocator_AqPYyD2Service.php', true],
    'App\\Controller\\EntrepriseController::enregistrer' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\EntrepriseController:depot' => ['privates', '.service_locator.aqPYyD2', 'get_ServiceLocator_AqPYyD2Service.php', true],
    'App\\Controller\\EntrepriseController:enregistrer' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\EntrepriseController::depot' => '?',
    'App\\Controller\\EntrepriseController::enregistrer' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\EntrepriseController:depot' => '?',
    'App\\Controller\\EntrepriseController:enregistrer' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
