<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQsidJBY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQsidJBY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQsidJBY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQsidJBY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQsidJBY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QsidJBY',
    'container.build_id' => 'f3362fa0',
    'container.build_time' => 1565090587,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQsidJBY');
