<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBoE4dK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBoE4dK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBoE4dK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBoE4dK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOBoE4dK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OBoE4dK',
    'container.build_id' => '9cec3e1b',
    'container.build_time' => 1565077554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBoE4dK');
